version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: benford_backend
    command: python benford_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migration:
    build: benford_backend
    command: python benford_backend/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      - db
  ng:
    container_name: ng
    build: benford_frontend
    ports:
      - "4200:8000"
    depends_on:
      - web
